name: CI

on:
  push:
    branches:
    - main

env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app

jobs:
  build-and-test:
    runs-on: macos-13

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: make build-debug-XcodeTestSample/XcodeTestSample.xcodeproj
